# Generated by Django 4.2.6 on 2023-10-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usertable_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
