# Generated by Django 4.2.6 on 2023-11-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_phone_number_usertable_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('document', models.FileField(upload_to='car_owner_documents/')),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=100)),
            ],
        ),
    ]
