# Generated by Django 4.2.6 on 2023-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='proposal_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
