# Generated by Django 4.2.6 on 2023-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_carowner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='proposal_status',
        ),
        migrations.AddField(
            model_name='carowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='venue_name',
            field=models.CharField(max_length=255),
        ),
    ]
