# Generated by Django 4.2.6 on 2023-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_carowner_is_active_carowner_proposal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='proposal_status',
            field=models.BooleanField(default=False),
        ),
    ]
