# Generated by Django 4.2.6 on 2023-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_carowner_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='proposal_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
