# Generated by Django 4.2.6 on 2023-11-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_carowner_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='password_generated',
            field=models.BooleanField(default=False),
        ),
    ]
